name:                gen-passwd
version:             1.1.0.0
synopsis:            Create wordlist-based passwords easily
description:         See README at <https://github.com/anfelor/gen-passwd#readme>
github:              anfelor/gen-passwd
license:             BSD3
author:              Anton Felix Lorenzen
maintainer:          Anton Felix Lorenzen <anfelor@posteo.de>
category:            CLI
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - vector
  - random
  - bytestring
  - optparse-applicative

executables:
  gen-passwd:
    source-dirs:      src
    main:             Main.hs
